// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"context"

	"test-question/internal/usecase/question/get_with_answers"

	"github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the useCase type
type UseCase struct {
	mock.Mock
}

// GetQuestionWithAnswers provides a mock function with given fields: ctx, questionID
func (_m *UseCase) GetQuestionWithAnswers(ctx context.Context, questionID int) (*get_with_answers.QuestionWithAnswers, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionWithAnswers")
	}

	var r0 *get_with_answers.QuestionWithAnswers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*get_with_answers.QuestionWithAnswers, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *get_with_answers.QuestionWithAnswers); ok {
		r0 = rf(ctx, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*get_with_answers.QuestionWithAnswers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
