// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// AnswerRepository is an autogenerated mock type for the answerRepository type
type AnswerRepository struct {
	mock.Mock
}

// DeleteByQuestionID provides a mock function with given fields: ctx, questionID
func (_m *AnswerRepository) DeleteByQuestionID(ctx context.Context, questionID int) error {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByQuestionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnswerRepository creates a new instance of AnswerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnswerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnswerRepository {
	mock := &AnswerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
