// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the useCase type
type UseCase struct {
	mock.Mock
}

// DeleteQuestion provides a mock function with given fields: ctx, questionID, userID
func (_m *UseCase) DeleteQuestion(ctx context.Context, questionID int, userID string) error {
	ret := _m.Called(ctx, questionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, questionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
