// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"test-question/internal/entity/question"
)

// QuestionRepository is an autogenerated mock type for the questionRepository type
type QuestionRepository struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx
func (_m *QuestionRepository) List(ctx context.Context) ([]*question.Question, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*question.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*question.Question, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*question.Question); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*question.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuestionRepository creates a new instance of QuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionRepository {
	mock := &QuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
