// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	answer "test-question/internal/entity/answer"

	mock "github.com/stretchr/testify/mock"
)

// AnswerRepository is an autogenerated mock type for the answerRepository type
type AnswerRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AnswerRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AnswerRepository) GetByID(ctx context.Context, id int) (*answer.Answer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *answer.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*answer.Answer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *answer.Answer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*answer.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnswerRepository creates a new instance of AnswerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnswerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnswerRepository {
	mock := &AnswerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
