// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	answer "test-question/internal/entity/answer"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the useCase type
type UseCase struct {
	mock.Mock
}

// CreateAnswer provides a mock function with given fields: ctx, questionID, userID, text
func (_m *UseCase) CreateAnswer(ctx context.Context, questionID int, userID string, text string) (*answer.Answer, error) {
	ret := _m.Called(ctx, questionID, userID, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnswer")
	}

	var r0 *answer.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) (*answer.Answer, error)); ok {
		return rf(ctx, questionID, userID, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) *answer.Answer); ok {
		r0 = rf(ctx, questionID, userID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*answer.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, questionID, userID, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
