// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"test-question/internal/entity/question"
)

// QuestionRepository is an autogenerated mock type for the questionRepository type
type QuestionRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *QuestionRepository) GetByID(ctx context.Context, id int) (*question.Question, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *question.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*question.Question, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *question.Question); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*question.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuestionRepository creates a new instance of QuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionRepository {
	mock := &QuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
